catalog:
  tag: "afd2bc"
orders_db:
  tag: "4899dd"
catalog_db:
  tag: "afd2bc"
cart:
  tag: "e38d71"
cart_dynamodb:
  tag: "e38d71"
orders:
  tag: "4899dd"
orders_db_rabbitmq:
  tag: "4899dd"
checkout:
  tag: "1b00c5"
checkout_db:
  tag: "1b00c5"
assets:
  tag: "586462"
ui:
  tag: "df0705"
